version: '3.8'

services:
  mailer:
    container_name: mailer
    extends:
      file: docker-compose.prod.yml
      service: mailer
    build:
      target: dependencies
    ports:
      - 9229:9229
    env_file:
      - .env.local
    # environment:
    #   - MAIL_DRIVER=mailgun
    #   - MAILGUN_API_KEY=test
    #   - MAILGUN_DOMAIN=mail.loicmazuel.com
    #   - MAILGUN_BASE_URL=https://api.eu.mailgun.net/v3
    #   - SENDER_MAIL=me@loicmazuel.com
    #   - SENDER_NAME="Team EspaceSingulier"
    #   - REPLY_TO_MAIL=me@loicmazuel.com
    #   - REPLY_TO_NAME="Team EspaceSingulier"
    volumes:
      - ./:/app
      - /app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"