version: '3.8'

services:
  api:
    restart: always
    extends:
      file: docker-compose.prod.yml
      service: api
    build:
      context: .
      target: dependencies
      args:
        - NODE_IMAGE=node:18-alpine3.15
    ports:
      - 3333:3333
      - 9229:9229
    env_file:
      - .env.local
    volumes:
      - ./:/app
      - /app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
