version: '3.8'

services:
  mailer:
    restart: always
    extends:
      file: docker-compose.prod.yml
      service: mailer
    container_name: mailer
    build:
      context: .
      target: installer
    ports:
      - 3333:3333
      - 9229:9229
    environment:
      - CORS_ORIGIN=*
      - SENDER_MAIL=me@loicmazuel.com
      - SENDER_NAME="Team Maz"
      - REPLY_TO_MAIL=me@loicmazuel.com
      - REPLY_TO_NAME="Team Maz"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    command: dumb-init node ace serve --watch --node-args="--inspect=0.0.0.0"
